# Generated by Django 4.2.11 on 2024-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking_app', '0005_hotelbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_in_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_out_date',
            field=models.CharField(max_length=100),
        ),
    ]
